version: 2
jobs:
  checkout:
    docker:
    - image: circleci/php:7.1
    steps:
    - restore_cache:
        key: repo-{{ .Branch }}
    - checkout
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - save_cache:
        key: repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
        paths:
        - ~/project

  should_build:
    docker:
    - image: circleci/php:7.1
    steps:
    - restore_cache:
        key: repo-{{ .Branch }}
    - checkout
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - run:
        name: Should Cancel?
        command: |
          cd ~/project
          ISBUILD=$(git log -1 --pretty=%B | grep "ci-build" | wc -l || true)
          if [ "$ISBUILD" -gt 0 ]
          then
            curl -X POST https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/cancel?circle-token=$CIRCLECI_TOKEN
            sleep 30
          fi
    - save_cache:
        key: repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
        paths:
          - ~/project

  php_test:
    docker:
      - image: circleci/php:7.1
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
      - run: composer install
      - run:
          name: Result Class CodeGen
          command: php codegen/generate.php
      - run:
          name: Run PHP Unit Tests
          command: ./vendor/bin/phpunit
      - store_test_results:
          path: test-results
      - run:
          name: Create docs
          command: ./vendor/bin/phpdoc
      - save_cache:
          key: codegen-{{ checksum ".circle-sha" }}
          paths:
            - ~/project/src

  deploy_to_github:
    docker:
    - image: circleci/php:7.1
    steps:
    - run: echo $CIRCLE_SHA1 > .circle-sha
    - restore_cache:
        key: repo-{{ .Branch }}-{{ checksum ".circle-sha" }}
    - restore_cache:
        key: codegen-{{ checksum ".circle-sha" }}
    - add-ssh-keys:
        fingerprints:
        - "5e:6c:f7:69:68:88:a7:a1:1a:c5:81:a2:c4:7d:c1:be"
    - run:
        command: |
          rm .circle-sha
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git add .
          git status
          git config --global user.email webmaster@tpt.org
          git config --global user.name tptwebmaster
          git diff-index --quiet HEAD || git commit -m 'Circle Build [ci-build]'
          git push origin $CIRCLE_BRANCH

workflows:
  version: 2
  staging:
    jobs:
    - should_build:
        context: staging
        filters:
          branches:
            only:
            - qa
    - php_test:
        requires:
        - should_build
    - deploy_to_github:
        requires:
        - php_test

  production:
    jobs:
    - should_build:
        context: production
        filters:
          branches:
            only:
            - master
    - php_test:
        requires:
        - should_build

  test:
    jobs:
    - checkout:
        filters:
          branches:
            ignore:
            - qa
            - hotfix
            - master
    - php_test:
        requires:
        - checkout